// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/protobufs/shared/topic.proto

package shared

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _topic_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on TopicBase with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *TopicBase) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopicBaseValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Title

	// no validation rules for LastReplyAt

	return nil
}

// TopicBaseValidationError is the validation error returned by
// TopicBase.Validate if the designated constraints aren't met.
type TopicBaseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopicBaseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopicBaseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopicBaseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopicBaseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopicBaseValidationError) ErrorName() string { return "TopicBaseValidationError" }

// Error satisfies the builtin error interface
func (e TopicBaseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopicBase.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopicBaseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopicBaseValidationError{}
