// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: internal/protobufs/shared/topic.proto

package shared

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TopicBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author      *UserBase `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title       string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	LastReplyAt string    `protobuf:"bytes,4,opt,name=last_reply_at,json=lastReplyAt,proto3" json:"last_reply_at,omitempty"`
}

func (x *TopicBase) Reset() {
	*x = TopicBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobufs_shared_topic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicBase) ProtoMessage() {}

func (x *TopicBase) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobufs_shared_topic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicBase.ProtoReflect.Descriptor instead.
func (*TopicBase) Descriptor() ([]byte, []int) {
	return file_internal_protobufs_shared_topic_proto_rawDescGZIP(), []int{0}
}

func (x *TopicBase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopicBase) GetAuthor() *UserBase {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *TopicBase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicBase) GetLastReplyAt() string {
	if x != nil {
		return x.LastReplyAt
	}
	return ""
}

var File_internal_protobufs_shared_topic_proto protoreflect.FileDescriptor

var file_internal_protobufs_shared_topic_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x1a,
	0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x42, 0x61,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x41, 0x74, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x63, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobufs_shared_topic_proto_rawDescOnce sync.Once
	file_internal_protobufs_shared_topic_proto_rawDescData = file_internal_protobufs_shared_topic_proto_rawDesc
)

func file_internal_protobufs_shared_topic_proto_rawDescGZIP() []byte {
	file_internal_protobufs_shared_topic_proto_rawDescOnce.Do(func() {
		file_internal_protobufs_shared_topic_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobufs_shared_topic_proto_rawDescData)
	})
	return file_internal_protobufs_shared_topic_proto_rawDescData
}

var file_internal_protobufs_shared_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protobufs_shared_topic_proto_goTypes = []interface{}{
	(*TopicBase)(nil), // 0: shared.TopicBase
	(*UserBase)(nil),  // 1: shared.UserBase
}
var file_internal_protobufs_shared_topic_proto_depIdxs = []int32{
	1, // 0: shared.TopicBase.author:type_name -> shared.UserBase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protobufs_shared_topic_proto_init() }
func file_internal_protobufs_shared_topic_proto_init() {
	if File_internal_protobufs_shared_topic_proto != nil {
		return
	}
	file_internal_protobufs_shared_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_protobufs_shared_topic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobufs_shared_topic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobufs_shared_topic_proto_goTypes,
		DependencyIndexes: file_internal_protobufs_shared_topic_proto_depIdxs,
		MessageInfos:      file_internal_protobufs_shared_topic_proto_msgTypes,
	}.Build()
	File_internal_protobufs_shared_topic_proto = out.File
	file_internal_protobufs_shared_topic_proto_rawDesc = nil
	file_internal_protobufs_shared_topic_proto_goTypes = nil
	file_internal_protobufs_shared_topic_proto_depIdxs = nil
}
