// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/protobufs/user/domain.proto

package user

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _domain_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on UserEntity with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserEntity) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Loginname

	// no validation rules for AvatarUrl

	return nil
}

// UserEntityValidationError is the validation error returned by
// UserEntity.Validate if the designated constraints aren't met.
type UserEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEntityValidationError) ErrorName() string { return "UserEntityValidationError" }

// Error satisfies the builtin error interface
func (e UserEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEntityValidationError{}

// Validate checks the field values on UserDetail with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserDetail) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Loginname

	// no validation rules for AvatarUrl

	// no validation rules for GithubUsername

	// no validation rules for CreateAt

	// no validation rules for Score

	for idx, item := range m.GetRecentTopics() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserDetailValidationError{
					field:  fmt.Sprintf("RecentTopics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetRecentReplies() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserDetailValidationError{
					field:  fmt.Sprintf("RecentReplies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// UserDetailValidationError is the validation error returned by
// UserDetail.Validate if the designated constraints aren't met.
type UserDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDetailValidationError) ErrorName() string { return "UserDetailValidationError" }

// Error satisfies the builtin error interface
func (e UserDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDetailValidationError{}
