// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: internal/protobufs/user/service.proto

package user

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetUserByLoginnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loginname string `protobuf:"bytes,1,opt,name=loginname,proto3" json:"loginname,omitempty"`
}

func (x *GetUserByLoginnameRequest) Reset() {
	*x = GetUserByLoginnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobufs_user_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByLoginnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginnameRequest) ProtoMessage() {}

func (x *GetUserByLoginnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobufs_user_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginnameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByLoginnameRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobufs_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByLoginnameRequest) GetLoginname() string {
	if x != nil {
		return x.Loginname
	}
	return ""
}

var File_internal_protobufs_user_service_proto protoreflect.FileDescriptor

var file_internal_protobufs_user_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x25, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0x50, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x72, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2d,
	0x63, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobufs_user_service_proto_rawDescOnce sync.Once
	file_internal_protobufs_user_service_proto_rawDescData = file_internal_protobufs_user_service_proto_rawDesc
)

func file_internal_protobufs_user_service_proto_rawDescGZIP() []byte {
	file_internal_protobufs_user_service_proto_rawDescOnce.Do(func() {
		file_internal_protobufs_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobufs_user_service_proto_rawDescData)
	})
	return file_internal_protobufs_user_service_proto_rawDescData
}

var file_internal_protobufs_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protobufs_user_service_proto_goTypes = []interface{}{
	(*GetUserByLoginnameRequest)(nil), // 0: user.GetUserByLoginnameRequest
	(*User)(nil),                      // 1: user.User
}
var file_internal_protobufs_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.GetUserByLoginname:input_type -> user.GetUserByLoginnameRequest
	1, // 1: user.UserService.GetUserByLoginname:output_type -> user.User
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protobufs_user_service_proto_init() }
func file_internal_protobufs_user_service_proto_init() {
	if File_internal_protobufs_user_service_proto != nil {
		return
	}
	file_internal_protobufs_user_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_protobufs_user_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByLoginnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobufs_user_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobufs_user_service_proto_goTypes,
		DependencyIndexes: file_internal_protobufs_user_service_proto_depIdxs,
		MessageInfos:      file_internal_protobufs_user_service_proto_msgTypes,
	}.Build()
	File_internal_protobufs_user_service_proto = out.File
	file_internal_protobufs_user_service_proto_rawDesc = nil
	file_internal_protobufs_user_service_proto_goTypes = nil
	file_internal_protobufs_user_service_proto_depIdxs = nil
}
