// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/protobufs/user/service.proto

package user

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetUserByLoginnameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetUserByLoginnameRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetLoginname()) != 1 {
		return GetUserByLoginnameRequestValidationError{
			field:  "Loginname",
			reason: "value length must be 1 runes",
		}

	}

	return nil
}

// GetUserByLoginnameRequestValidationError is the validation error returned by
// GetUserByLoginnameRequest.Validate if the designated constraints aren't met.
type GetUserByLoginnameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserByLoginnameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserByLoginnameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserByLoginnameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserByLoginnameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserByLoginnameRequestValidationError) ErrorName() string {
	return "GetUserByLoginnameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserByLoginnameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserByLoginnameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserByLoginnameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserByLoginnameRequestValidationError{}

// Validate checks the field values on GetUserByLoginnameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetUserByLoginnameResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserByLoginnameResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Success

	return nil
}

// GetUserByLoginnameResponseValidationError is the validation error returned
// by GetUserByLoginnameResponse.Validate if the designated constraints aren't met.
type GetUserByLoginnameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserByLoginnameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserByLoginnameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserByLoginnameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserByLoginnameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserByLoginnameResponseValidationError) ErrorName() string {
	return "GetUserByLoginnameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserByLoginnameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserByLoginnameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserByLoginnameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserByLoginnameResponseValidationError{}

// Validate checks the field values on ValidateAccessTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ValidateAccessTokenRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Accesstoken

	return nil
}

// ValidateAccessTokenRequestValidationError is the validation error returned
// by ValidateAccessTokenRequest.Validate if the designated constraints aren't met.
type ValidateAccessTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateAccessTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateAccessTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateAccessTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateAccessTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateAccessTokenRequestValidationError) ErrorName() string {
	return "ValidateAccessTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateAccessTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateAccessTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateAccessTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateAccessTokenRequestValidationError{}

// Validate checks the field values on ValidateAccessTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ValidateAccessTokenResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Loginname

	// no validation rules for AvatarUrl

	// no validation rules for Success

	return nil
}

// ValidateAccessTokenResponseValidationError is the validation error returned
// by ValidateAccessTokenResponse.Validate if the designated constraints
// aren't met.
type ValidateAccessTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateAccessTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateAccessTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateAccessTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateAccessTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateAccessTokenResponseValidationError) ErrorName() string {
	return "ValidateAccessTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateAccessTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateAccessTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateAccessTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateAccessTokenResponseValidationError{}
