// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/protobufs/topic/domain.proto

package topic

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _domain_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Topic with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Topic) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for AuthorId

	// no validation rules for Tab

	// no validation rules for Title

	// no validation rules for Content

	if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopicValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Good

	// no validation rules for Top

	// no validation rules for ReplyCount

	// no validation rules for VisitCount

	// no validation rules for CreateAt

	// no validation rules for LastReplyAt

	return nil
}

// TopicValidationError is the validation error returned by Topic.Validate if
// the designated constraints aren't met.
type TopicValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopicValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopicValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopicValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopicValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopicValidationError) ErrorName() string { return "TopicValidationError" }

// Error satisfies the builtin error interface
func (e TopicValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopic.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopicValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopicValidationError{}

// Validate checks the field values on TopicDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TopicDetail) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for AuthorId

	// no validation rules for Tab

	// no validation rules for Title

	// no validation rules for Content

	if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopicDetailValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Good

	// no validation rules for Top

	// no validation rules for ReplyCount

	// no validation rules for VisitCount

	// no validation rules for CreateAt

	// no validation rules for LastReplyAt

	for idx, item := range m.GetReplies() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TopicDetailValidationError{
					field:  fmt.Sprintf("Replies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IsCollect

	return nil
}

// TopicDetailValidationError is the validation error returned by
// TopicDetail.Validate if the designated constraints aren't met.
type TopicDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopicDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopicDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopicDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopicDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopicDetailValidationError) ErrorName() string { return "TopicDetailValidationError" }

// Error satisfies the builtin error interface
func (e TopicDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopicDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopicDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopicDetailValidationError{}
